language: node_js
node_js: stable
cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  provider: pages
  local-dir: doc/.vuepress/dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master